### ISSUE TITLE
Add: Donated Items Page

### ISSUE THREAD

**Issue by androidmini9x** [ReCoded-Org/capstone-turkey-react-paying-it-forward#14]
Is your feature request related to a problem? Please describe.

Donated Items Page is the page the hold and shows us all the available items.

----------------------------------------------

Describe how the solution should behave:

Fetch all the items from the backend into a slice called `items`.

Showcase the whole items on the Items page.

Once the user clicks on an item, they should move to the detailed item view via the router (take the item id and use it in the router) -in a modal or as a separate page- which will showcase the details and the owner of that item.

We should be able to filter the items via the buttons.

The item must be disabled when the count and the borrowers are equal. (isAvailable flag must be turned to false and the item must not render on the donated items page)

[Items Endpoint](https://payingitforward.re-coded.com/api/docs/#/Items/get_items_available)
[Filter Endpoint](https://payingitforward.re-coded.com/api/docs/#/Items/get_items_filter)
[Specific Item Endpoint](https://payingitforward.re-coded.com/api/docs/#/Items/get_items__id_)

--------------------------

Screenshots of the design/if any
![Screenshot from 2022-04-11 21-32-23](https://user-images.githubusercontent.com/97795729/162806255-7c10e6ab-5176-49b0-b8b1-acb459f706d1.png)

--------------------------

Additional context
N/A
-----------------

**Comment by Iseluin** [comment]
Same with this issue @androidmini9x , please do not rush with the store but go ahead and create the filter buttons, the container div and the page header.
