### ISSUE TITLE
Add: Requested Items Page

### ISSUE THREAD

**Issue by androidmini9x** [ReCoded-Org/capstone-turkey-react-paying-it-forward#15]
Is your feature request related to a problem? Please describe.

Requested Items Page is the page the hold and shows us all the requested items.

-----------------

Describe how the solution should behave:

Fetch all the requests from the backend into a slice called `requests`.

Showcase the whole requests on the Requested Items page.

Once the user clicks on a request, they should move to the detailed request view via the router (take the request id and use it in the router) -in a modal or as a separate page- which will showcase the details and the owner of that request.

We should be able to filter the requests via the buttons.

[Requests Endpoint](https://payingitforward.re-coded.com/api/docs/#/Requests/get_requests)
[Filter Endpoint](https://payingitforward.re-coded.com/api/docs/#/Items/get_items_filter)
[Specific Request Endpoint](https://payingitforward.re-coded.com/api/docs/#/Requests/get_requests__id_)

---------------------

Screenshots of the design/if any

![Screenshot from 2022-04-11 21-37-49](https://user-images.githubusercontent.com/97795729/162807036-3e107f4c-8990-4460-bf1f-269919bbd7ec.png)

-------------------

Additional context
N/A

-----------------

**Comment by Iseluin** [comment]
Great work on creating your own issue @androidmini9x, please do not rush with setting up the store for the api calls, I will distribute that task to a team of 2-3 people, but please go ahead and create the page, the div containers for it and the filter buttons you see in the page.
